# Generated by Django 3.1.7 on 2021-05-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApi', '0002_searcheddata_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searcheddata',
            name='response',
            field=models.JSONField(),
        ),
    ]
